name: CI

on: 
  push:
    branches : [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 8.15.1
      uses: actions/setup-node@v1
      with:
        node-version: 8.15.1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist/bruw
        BUILD_SCRIPT: npm install && npm run build -- --prod && cp dist/index.html dist/404.html &&  echo "whabitat.victordurand.fr" >> dist/bruw/CNAME
